FROM resin/%%BALENA_MACHINE_NAME%%-debian

RUN apt-get update && \
	apt-get install -yq git ssh && \
	apt-get clean && rm -rf /var/lib/apt/lists/*

RUN git config --global user.email "ezeward4@gmail.com" && \
	git config --global user.name "Eric Ward"

WORKDIR /config

CMD bash
